/**
 * UI chrome strings. Clinical content lives in content/i18n (per card, and
 * completeness-gated); this file is only the furniture around it.
 */
import { getLang, Lang } from './lang'

type Dict = Record<string, string>

const EN: Dict = {
  'lib.promise': 'Catch the cannot-miss ECGs — mechanism first, on real recordings.',
  'lib.search': 'Search patterns — “wide”, “AF”, “block”',
  'lib.about': 'About',
  'lib.drill': 'Drill',
  'lib.drill.fresh': 'unknown strips, no labels — cannot-miss first',
  'lib.drill.due': '{due} due for review · {solid}/{total} solid',
  'lib.drill.solid': '{solid}/{total} solid — cannot-miss first',
  'lib.sets': 'Curated sets',
  'lib.lethal': 'cannot-miss',
  'lib.lethalOnly': 'cannot-miss only',
  'lib.seen': 'seen',
  'lib.learning': 'learning',
  'lib.solid': 'solid',
  'lib.empty': 'Nothing matches “{q}”.',
  'lib.disclaimer': 'Educational — never a substitute for clinical judgment or local protocol.',
  'lab.electrodes': 'Electrode Lab',
  'lab.electrodes.sub': 'Drag the electrodes — the trace obeys.',
  'lab.hyperk': 'HyperK Lab',
  'lab.hyperk.sub': 'Five patients, one K⁺ — estimate it.',

  'card.back': 'Back to library',
  'card.allLeads': '12-lead',
  'lib.streakN': 'day {n}',
  'lib.proven': 'proven on real ECGs',
  'drill.sessionDone': 'Session complete',
  'drill.bestRun': 'Best run',
  'drill.streak': 'Day streak',
  'drill.streakChip': 'day {n}',
  'drill.due24': 'Due in the next 24 h',
  'drill.again': 'Another 10',
  'drill.home': 'Done for today',
  'drill.finish': 'Finish',
  'drill.measured': 'Measured on this strip',
  'drill.imperfect': 'Imperfect strip — like real life',
  'drill.drift': 'baseline drift',
  'drill.staticN': 'static/muscle noise',
  'drill.burst': 'transient artifact',
  'drill.electrodes': 'electrode problem',
  'drill.allLeadsTok': 'all leads',
  'drill.diffuse': 'diffuse',
  'about.metrics': 'Usage is measured anonymously: a random install id, which screens are used and whether answers are right — never your name, email, IP address or any patient data. No cookies. Do Not Track is honored.',
  'a11y.shareCard': 'Share this card',
  'a11y.chooseLeads': 'Choose leads',
  'a11y.highlightPhase': 'Highlight a phase',
  'a11y.audience': 'Audience',
  'a11y.speed': 'Playback speed',
  'a11y.language': 'Language',
  'a11y.search': 'Search patterns',
  'a11y.sets': 'Curated sets',
  'card.share': 'Share',
  'card.seeIt': 'See it',
  'card.why': 'Why',
  'card.pills': 'Pearls & traps',
  'card.suspect': 'Suspect & confirm',
  'card.moves': 'Guideline moves',
  'card.movesRn': 'Recognize & respond',
  'card.avoid': 'avoid',
  'card.commitHint': 'Commit a read — then the card opens.',
  'card.skip': 'skip — open as reference',
  'card.skipped': '· opened as reference',
  'card.recommit': 're-commit',
  'card.explain': 'explain more',
  'card.close': 'close',
  'card.youRead': 'You read:',
  'card.localProtocol': 'Verify against your local protocol.',
  'card.stamp': 'Checked against the cited guidelines · {date} — educational reference, not medical advice',
  'card.recordings': 'Recordings',
  'card.sameDx': 'same diagnosis, different patient',
  'card.showHeart': 'show heart',
  'card.hideHeart': 'hide',
  'card.highlight': 'highlight',
  'card.coachTrace': '↔ drag to scrub · pinch to zoom',
  'card.coachHeart': 'drag the heart to step through the beat — the trace follows',
  'card.validate': 'How we validate',
  'card.notDiagnosis': 'Education, not diagnosis',
  'card.englishOnly': 'Clinical content in English — Italian translation pending.',
  'card.library': 'library',

  'drill.title': 'Drill',
  'drill.prompt': 'Your read?',
  'drill.solid': '{solid}/{total} solid',
  'drill.whyTempted': 'Why it tempted:',
  'drill.missed': 'Missed — it comes back until it’s yours.',
  'drill.open': 'open the card →',
  'drill.next': 'Next strip',
  'drill.loading': 'loading strip…',

  'pack.finish': 'Finish',
  'pack.next': 'Next',
  'pack.done': 'Done',
  'pack.keepDrilling': 'keep drilling →',
  'pack.clean': 'Clean sweep — every read landed.',
  'pack.missed': 'The missed reads come back in the drill until they’re yours:',
  'pack.openFull': 'open the full card →',
}

const IT: Dict = {
  'lib.promise': 'Riconosci gli ECG che non puoi mancare — prima il meccanismo, su tracciati reali.',
  'lib.search': 'Cerca un quadro — “largo”, “FA”, “blocco”',
  'lib.about': 'Il metodo',
  'lib.drill': 'Allenamento',
  'lib.drill.fresh': 'tracciati senza nome — prima i non-mancabili',
  'lib.drill.due': '{due} da ripassare · {solid}/{total} solidi',
  'lib.drill.solid': '{solid}/{total} solidi — prima i non-mancabili',
  'lib.sets': 'Percorsi',
  'lib.lethal': 'da non mancare',
  'lib.lethalOnly': 'solo da non mancare',
  'lib.seen': 'visto',
  'lib.learning': 'in corso',
  'lib.solid': 'solido',
  'lib.empty': 'Nessun risultato per “{q}”.',
  'lib.disclaimer': 'Materiale didattico — non sostituisce il giudizio clinico né il protocollo locale.',
  'lab.electrodes': 'Laboratorio elettrodi',
  'lab.electrodes.sub': 'Sposta gli elettrodi — il tracciato obbedisce.',
  'lab.hyperk': 'Laboratorio K⁺',
  'lab.hyperk.sub': 'Cinque pazienti, un potassio — stimalo.',

  'card.back': 'Torna all’indice',
  'card.allLeads': '12 derivazioni',
  'lib.streakN': 'giorno {n}',
  'lib.proven': 'consolidato su ECG reali',
  'drill.sessionDone': 'Sessione completata',
  'drill.bestRun': 'Serie migliore',
  'drill.streak': 'Giorni di fila',
  'drill.streakChip': 'giorno {n}',
  'drill.due24': 'In scadenza nelle prossime 24 h',
  'drill.again': 'Altre 10',
  'drill.home': 'Basta per oggi',
  'drill.finish': 'Concludi',
  'drill.measured': 'Misurato su questo tracciato',
  'drill.imperfect': 'Tracciato imperfetto — come nella realtà',
  'drill.drift': 'deriva della linea di base',
  'drill.staticN': 'disturbo statico/muscolare',
  'drill.burst': 'artefatti transitori',
  'drill.electrodes': 'problema di elettrodo',
  'drill.allLeadsTok': 'tutte le derivazioni',
  'drill.diffuse': 'diffuso',
  'about.metrics': 'L’uso è misurato in forma anonima: un identificativo casuale di installazione, quali schermate vengono usate e se le risposte sono corrette — mai nome, email, indirizzo IP o dati di pazienti. Nessun cookie. Il Do Not Track è rispettato.',
  'a11y.shareCard': 'Condividi questa scheda',
  'a11y.chooseLeads': 'Scegli le derivazioni',
  'a11y.highlightPhase': 'Evidenzia una fase',
  'a11y.audience': 'Destinatario',
  'a11y.speed': 'Velocità di scorrimento',
  'a11y.language': 'Lingua',
  'a11y.search': 'Cerca un pattern',
  'a11y.sets': 'Percorsi curati',
  'card.share': 'Condividi',
  'card.seeIt': 'Guarda',
  'card.why': 'Perché',
  'card.pills': 'Perle e trappole',
  'card.suspect': 'Sospetta e conferma',
  'card.moves': 'Che cosa fare',
  'card.movesRn': 'Riconosci e agisci',
  'card.avoid': 'da evitare',
  'card.commitHint': 'Impegnati in una lettura — poi la scheda si apre.',
  'card.skip': 'salta — apri come consultazione',
  'card.skipped': '· aperta come consultazione',
  'card.recommit': 'rileggi',
  'card.explain': 'spiega meglio',
  'card.close': 'chiudi',
  'card.youRead': 'Hai letto:',
  'card.localProtocol': 'Verifica sempre sul tuo protocollo locale.',
  'card.stamp': 'Verificato sulle linee guida citate · {date} — materiale didattico, non consulenza medica',
  'card.recordings': 'Tracciati',
  'card.sameDx': 'stessa diagnosi, paziente diverso',
  'card.showHeart': 'mostra il cuore',
  'card.hideHeart': 'nascondi',
  'card.highlight': 'evidenzia',
  'card.coachTrace': '↔ trascina per scorrere · pizzica per ingrandire',
  'card.coachHeart': 'trascina il cuore per percorrere il battito — il tracciato segue',
  'card.validate': 'Come verifichiamo',
  'card.notDiagnosis': 'Didattica, non diagnosi',
  'card.englishOnly': 'Contenuto clinico in inglese — traduzione italiana in arrivo.',
  'card.library': 'indice',

  'drill.title': 'Allenamento',
  'drill.prompt': 'La tua lettura?',
  'drill.solid': '{solid}/{total} solidi',
  'drill.whyTempted': 'Perché ti ha tentato:',
  'drill.missed': 'Sbagliata — tornerà finché non sarà tua.',
  'drill.open': 'apri la scheda →',
  'drill.next': 'Prossimo tracciato',
  'drill.loading': 'caricamento tracciato…',

  'pack.finish': 'Fine',
  'pack.next': 'Avanti',
  'pack.done': 'Chiudi',
  'pack.keepDrilling': 'continua ad allenarti →',
  'pack.clean': 'En plein — tutte le letture giuste.',
  'pack.missed': 'Le letture sbagliate tornano nell’allenamento finché non saranno tue:',
  'pack.openFull': 'apri la scheda completa →',
}

const DICTS: Record<Lang, Dict> = { en: EN, it: IT }

/** Translate a chrome key, with {placeholder} interpolation. */
export const t = (key: string, vars?: Record<string, string | number>): string => {
  const raw = DICTS[getLang()][key] ?? EN[key] ?? key
  if (!vars) return raw
  return raw.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`))
}

/** Keys present in EN — used by the validator to catch drift. */
export const UI_KEYS = Object.keys(EN)
export const UI_DICTS = DICTS
