/**
 * AUTO-GENERATED by tools/recordings/build-quiz-bank.mjs — do not edit.
 * Every strip is a cardiologist-validated PTB-XL recording (CC BY 4.0) that
 * ALSO passed its class's measurement gate on the raw signal; `f` holds the
 * measured findings the drill shows on reveal.
 */
export interface QuizFindings {
  rate: number
  rrCv: number
  qrs: number
  qtc?: number
  pr?: number
  stMax?: [string, number]
  stMin?: [string, number]
  sokolow?: number
}
export interface QuizStrip { traceId: string; cardId: string; f: QuizFindings }

export const QUIZ_STRIPS: QuizStrip[] = [
  { traceId: 'qs-20', cardId: 'aflutter', f: {"rate":140,"rrCv":1,"qrs":91,"stMax":["aVR",0.11],"stMin":["II",-0.19]} },
  { traceId: 'qs-39', cardId: 'longqt', f: {"rate":88,"rrCv":1.2,"qrs":98,"qtc":665} },
  { traceId: 'qs-53', cardId: 'nsr', f: {"rate":74,"rrCv":3.8,"qrs":74,"pr":172,"stMax":["V2",0.08]} },
  { traceId: 'qs-62', cardId: 'nsr', f: {"rate":71,"rrCv":2.6,"qrs":76,"pr":170,"stMax":["V2",0.16]} },
  { traceId: 'qs-71', cardId: 'nsr', f: {"rate":70,"rrCv":2.2,"qrs":96,"pr":174,"stMax":["V2",0.15]} },
  { traceId: 'qs-89', cardId: 'nsr', f: {"rate":55,"rrCv":5.8,"qrs":96,"pr":162,"stMax":["V2",0.13]} },
  { traceId: 'qs-107', cardId: 'nsr', f: {"rate":79,"rrCv":1.3,"qrs":78,"pr":136,"stMax":["V3",0.1]} },
  { traceId: 'qs-111', cardId: 'nsr', f: {"rate":65,"rrCv":4,"qrs":100,"pr":174,"stMax":["V3",0.14]} },
  { traceId: 'qs-112', cardId: 'nsr', f: {"rate":71,"rrCv":2.6,"qrs":88,"pr":124,"stMax":["V2",0.21]} },
  { traceId: 'qs-156', cardId: 'nsr', f: {"rate":74,"rrCv":1.7,"qrs":98,"pr":132,"stMax":["V2",0.16]} },
  { traceId: 'qs-172', cardId: 'rbbb', f: {"rate":81,"rrCv":0.8,"qrs":136,"pr":153,"stMin":["V3",-0.17]} },
  { traceId: 'qs-183', cardId: 'nsr', f: {"rate":79,"rrCv":1.3,"qrs":88,"pr":178,"stMax":["V3",0.11]} },
  { traceId: 'qs-196', cardId: 'nsr', f: {"rate":57,"rrCv":0.6,"qrs":84,"pr":176,"stMax":["V2",0.13]} },
  { traceId: 'qs-307', cardId: 'afib', f: {"rate":63,"rrCv":30.7,"qrs":90,"stMax":["V3",0.17],"stMin":["V5",-0.11],"sokolow":3.7} },
  { traceId: 'qs-310', cardId: 'rbbb', f: {"rate":59,"rrCv":1.2,"qrs":156,"pr":214,"stMin":["V4",-0.1]} },
  { traceId: 'qs-321', cardId: 'afib', f: {"rate":101,"rrCv":24.6,"qrs":98,"stMax":["V2",0.16]} },
  { traceId: 'qs-337', cardId: 'afib', f: {"rate":90,"rrCv":22.8,"qrs":88,"stMax":["V2",0.13],"sokolow":3.9} },
  { traceId: 'qs-424', cardId: 'rbbb', f: {"rate":72,"rrCv":1,"qrs":130,"pr":260,"stMin":["V1",-0.08]} },
  { traceId: 'qs-449', cardId: 'aflutter', f: {"rate":173,"rrCv":4.2,"qrs":74,"stMin":["V4",-0.09]} },
  { traceId: 'qs-452', cardId: 'afib', f: {"rate":73,"rrCv":18.3,"qrs":100,"stMin":["V5",-0.15],"sokolow":4.5} },
  { traceId: 'qs-455', cardId: 'rbbb', f: {"rate":74,"rrCv":1,"qrs":164,"pr":260,"stMax":["III",0.47],"stMin":["V3",-0.42]} },
  { traceId: 'qs-482', cardId: 'afib', f: {"rate":110,"rrCv":22.9,"qrs":112,"stMax":["V5",0.11]} },
  { traceId: 'qs-530', cardId: 'omi-anterior', f: {"rate":64,"rrCv":7.2,"qrs":122,"pr":247,"stMax":["V2",0.26],"stMin":["V6",-0.12]} },
  { traceId: 'qs-557', cardId: 'afib', f: {"rate":74,"rrCv":21.8,"qrs":96,"stMax":["V2",0.17]} },
  { traceId: 'qs-608', cardId: 'afib', f: {"rate":127,"rrCv":27.4,"qrs":102,"stMax":["V2",0.36],"stMin":["V6",-0.13]} },
  { traceId: 'qs-610', cardId: 'afib', f: {"rate":79,"rrCv":15.4,"qrs":102,"stMin":["I",-0.1]} },
  { traceId: 'qs-656', cardId: 'afib', f: {"rate":69,"rrCv":23.4,"qrs":78} },
  { traceId: 'qs-674', cardId: 'afib', f: {"rate":83,"rrCv":29.7,"qrs":105,"stMax":["V4",0.11],"stMin":["V6",-0.5]} },
  { traceId: 'qs-706', cardId: 'aflutter', f: {"rate":72,"rrCv":14.6,"qrs":92} },
  { traceId: 'qs-743', cardId: 'longqt', f: {"rate":84,"rrCv":1.4,"qrs":82,"qtc":628,"stMin":["V5",-0.1]} },
  { traceId: 'qs-788', cardId: 'rbbb', f: {"rate":55,"rrCv":1.1,"qrs":138,"pr":190,"stMax":["V4",0.16],"stMin":["V1",-0.1]} },
  { traceId: 'qs-840', cardId: 'longqt', f: {"rate":74,"rrCv":2,"qrs":86,"pr":218,"stMin":["V5",-0.16]} },
  { traceId: 'qs-871', cardId: 'rbbb', f: {"rate":87,"rrCv":4.3,"qrs":132,"stMax":["II",0.08]} },
  { traceId: 'qs-912', cardId: 'omi-anterior', f: {"rate":66,"rrCv":3.2,"qrs":110,"pr":186,"stMax":["V3",0.14]} },
  { traceId: 'qs-919', cardId: 'wellens', f: {"rate":56,"rrCv":29.9,"qrs":82,"pr":173} },
  { traceId: 'qs-1066', cardId: 'rbbb', f: {"rate":76,"rrCv":1.7,"qrs":158} },
  { traceId: 'qs-1072', cardId: 'lbbb', f: {"rate":69,"rrCv":1.1,"qrs":138,"pr":260,"stMax":["V3",0.39],"stMin":["V6",-0.08]} },
  { traceId: 'qs-1138', cardId: 'omi-anterior', f: {"rate":69,"rrCv":1.3,"qrs":100,"pr":260,"stMax":["III",0.16],"stMin":["aVL",-0.1]} },
  { traceId: 'qs-1173', cardId: 'aflutter', f: {"rate":164,"rrCv":1.4,"qrs":81,"stMax":["V2",0.26],"stMin":["II",-0.17]} },
  { traceId: 'qs-1222', cardId: 'avb-2', f: {"rate":55,"rrCv":30.2,"qrs":130,"pr":260} },
  { traceId: 'qs-1367', cardId: 'lbbb', f: {"rate":64,"rrCv":6.4,"qrs":150,"pr":260,"stMax":["V2",0.85],"stMin":["aVL",-0.12],"sokolow":4.9} },
  { traceId: 'qs-1437', cardId: 'rbbb', f: {"rate":68,"rrCv":1.2,"qrs":170,"pr":260,"stMax":["III",0.44],"stMin":["V3",-0.36]} },
  { traceId: 'qs-1492', cardId: 'rbbb', f: {"rate":64,"rrCv":3.1,"qrs":158,"pr":219,"stMax":["V4",0.16]} },
  { traceId: 'qs-1687', cardId: 'omi-anterior', f: {"rate":93,"rrCv":0.9,"qrs":98,"stMax":["III",0.19],"stMin":["I",-0.18]} },
  { traceId: 'qs-1919', cardId: 'svt-avnrt', f: {"rate":171,"rrCv":0.8,"qrs":68,"stMax":["V2",0.1]} },
  { traceId: 'qs-2034', cardId: 'rbbb', f: {"rate":79,"rrCv":2.4,"qrs":137,"pr":162,"stMax":["V4",0.14],"stMin":["V1",-0.09]} },
  { traceId: 'qs-2136', cardId: 'lbbb', f: {"rate":80,"rrCv":3.6,"qrs":142,"stMax":["V2",0.73],"stMin":["V6",-0.35],"sokolow":4.1} },
  { traceId: 'qs-2218', cardId: 'paced-v', f: {"rate":80,"rrCv":0.2,"qrs":180,"stMax":["V4",0.85],"stMin":["aVR",-0.52]} },
  { traceId: 'qs-2221', cardId: 'longqt', f: {"rate":79,"rrCv":3.7,"qrs":78,"qtc":603,"pr":180} },
  { traceId: 'qs-2365', cardId: 'lbbb', f: {"rate":74,"rrCv":1.4,"qrs":174,"pr":169,"stMax":["V2",0.87],"stMin":["I",-0.2],"sokolow":4.1} },
  { traceId: 'qs-2412', cardId: 'omi-anterior', f: {"rate":61,"rrCv":2.1,"qrs":86,"pr":246,"stMax":["V1",0.26],"sokolow":4.2} },
  { traceId: 'qs-2795', cardId: 'aflutter', f: {"rate":149,"rrCv":2.4,"qrs":112,"stMax":["V2",0.61],"stMin":["V5",-0.22]} },
  { traceId: 'qs-2992', cardId: 'omi-anterior', f: {"rate":67,"rrCv":2.8,"qrs":86,"stMax":["V2",0.26],"stMin":["aVL",-0.14],"sokolow":3.5} },
  { traceId: 'qs-3037', cardId: 'lbbb', f: {"rate":56,"rrCv":4.4,"qrs":168,"pr":188,"stMax":["V3",0.8],"stMin":["V6",-0.18]} },
  { traceId: 'qs-3038', cardId: 'lvh-strain', f: {"rate":75,"rrCv":9.8,"qrs":86,"pr":260,"stMax":["V2",0.14],"stMin":["aVL",-0.08],"sokolow":3.8} },
  { traceId: 'qs-3304', cardId: 'lbbb', f: {"rate":69,"rrCv":1.8,"qrs":148,"pr":198,"stMax":["V2",0.81],"stMin":["V6",-0.09],"sokolow":3.9} },
  { traceId: 'qs-3306', cardId: 'aflutter', f: {"rate":142,"rrCv":0.5,"qrs":80,"stMax":["V2",0.16],"stMin":["III",-0.19]} },
  { traceId: 'qs-3473', cardId: 'omi-anterior', f: {"rate":92,"rrCv":8.6,"qrs":126,"stMax":["V2",0.45],"stMin":["aVL",-0.09]} },
  { traceId: 'qs-3476', cardId: 'svt-avnrt', f: {"rate":169,"rrCv":0.9,"qrs":78,"stMax":["aVR",0.11],"stMin":["II",-0.13]} },
  { traceId: 'qs-3672', cardId: 'paced-v', f: {"rate":137,"rrCv":0.7,"qrs":148,"stMax":["III",0.48],"stMin":["aVL",-0.37]} },
  { traceId: 'qs-3723', cardId: 'paced-v', f: {"rate":70,"rrCv":1.2,"qrs":194,"stMax":["V3",0.54],"stMin":["aVL",-0.2]} },
  { traceId: 'qs-4016', cardId: 'lbbb', f: {"rate":70,"rrCv":0.9,"qrs":160,"pr":148,"stMax":["V2",0.29],"stMin":["I",-0.16]} },
  { traceId: 'qs-4108', cardId: 'lvh-strain', f: {"rate":88,"rrCv":2,"qrs":72,"qtc":632,"stMax":["V1",0.08],"stMin":["V5",-0.11],"sokolow":4.1} },
  { traceId: 'qs-4148', cardId: 'lbbb', f: {"rate":70,"rrCv":0.7,"qrs":136,"pr":200,"stMax":["V3",0.31]} },
  { traceId: 'qs-4415', cardId: 'lbbb', f: {"rate":59,"rrCv":1.5,"qrs":172,"pr":154,"stMax":["V2",0.16],"stMin":["V6",-0.12]} },
  { traceId: 'qs-4560', cardId: 'lbbb', f: {"rate":62,"rrCv":0.6,"qrs":168,"pr":242,"stMax":["V2",0.75],"stMin":["I",-0.18]} },
  { traceId: 'qs-4838', cardId: 'avb-3', f: {"rate":50,"rrCv":2.1,"qrs":82,"pr":260,"stMax":["III",0.09],"stMin":["V4",-0.16]} },
  { traceId: 'qs-5994', cardId: 'longqt', f: {"rate":104,"rrCv":1.7,"qrs":88,"qtc":696} },
  { traceId: 'qs-6068', cardId: 'lvh-strain', f: {"rate":71,"rrCv":0.9,"qrs":80,"qtc":489,"pr":172,"stMax":["V2",0.1],"stMin":["V4",-0.1],"sokolow":4.7} },
  { traceId: 'qs-6240', cardId: 'wpw', f: {"rate":79,"rrCv":0.9,"qrs":187,"pr":260,"stMax":["III",0.6],"stMin":["aVL",-0.53]} },
  { traceId: 'qs-6310', cardId: 'longqt', f: {"rate":59,"rrCv":4.7,"qrs":98,"qtc":542,"pr":238,"stMax":["V2",0.12]} },
  { traceId: 'qs-7445', cardId: 'paced-v', f: {"rate":70,"rrCv":0.1,"qrs":208,"stMax":["V4",0.69],"stMin":["aVL",-0.15]} },
  { traceId: 'qs-7889', cardId: 'svt-avnrt', f: {"rate":160,"rrCv":2.4,"qrs":84,"stMax":["V1",0.15],"stMin":["I",-0.11]} },
  { traceId: 'qs-8194', cardId: 'lvh-strain', f: {"rate":86,"rrCv":0.8,"qrs":92,"stMax":["V2",0.2],"sokolow":4.5} },
  { traceId: 'qs-8911', cardId: 'avb-3', f: {"rate":38,"rrCv":0.1,"qrs":93,"pr":260,"stMax":["V6",0.14],"stMin":["V1",-0.08]} },
  { traceId: 'qs-9795', cardId: 'wpw', f: {"rate":51,"rrCv":1.9,"qrs":144,"pr":117,"stMax":["V1",0.25],"stMin":["V5",-0.19],"sokolow":4.6} },
  { traceId: 'qs-9823', cardId: 'wpw', f: {"rate":64,"rrCv":1.2,"qrs":118,"pr":129,"stMax":["V2",0.16],"stMin":["V6",-0.19],"sokolow":3.5} },
  { traceId: 'qs-9866', cardId: 'svt-avnrt', f: {"rate":160,"rrCv":0.6,"qrs":74,"stMax":["V2",0.13]} },
  { traceId: 'qs-9925', cardId: 'lvh-strain', f: {"rate":81,"rrCv":5.1,"qrs":78,"qtc":609,"pr":221,"stMin":["V6",-0.09],"sokolow":3.6} },
  { traceId: 'qs-10243', cardId: 'leftmain', f: {"rate":100,"rrCv":2.1,"qrs":106,"pr":148,"stMax":["aVR",0.09],"stMin":["V6",-0.21]} },
  { traceId: 'qs-10306', cardId: 'svt-avnrt', f: {"rate":152,"rrCv":0.4,"qrs":78,"stMax":["aVR",0.12],"stMin":["V4",-0.18]} },
  { traceId: 'qs-11889', cardId: 'wpw', f: {"rate":59,"rrCv":1.7,"qrs":194,"pr":260,"stMax":["V1",0.27],"stMin":["II",-0.3]} },
  { traceId: 'qs-12292', cardId: 'paced-v', f: {"rate":72,"rrCv":0.2,"qrs":190,"stMax":["V3",0.8],"stMin":["aVL",-0.35]} },
  { traceId: 'qs-12325', cardId: 'lvh-strain', f: {"rate":76,"rrCv":1.1,"qrs":72,"pr":156,"stMax":["V2",0.22],"sokolow":5.8} },
  { traceId: 'qs-12559', cardId: 'wpw', f: {"rate":70,"rrCv":7.3,"qrs":134,"pr":126,"stMax":["V1",0.15],"stMin":["V4",-0.19]} },
  { traceId: 'qs-13779', cardId: 'omi-anterior', f: {"rate":51,"rrCv":1.3,"qrs":90,"pr":138,"stMax":["V2",0.17],"stMin":["V5",-0.08]} },
  { traceId: 'qs-13938', cardId: 'avb-2', f: {"rate":68,"rrCv":30.1,"qrs":78,"pr":260} },
  { traceId: 'qs-14609', cardId: 'paced-v', f: {"rate":70,"rrCv":0.1,"qrs":198,"stMax":["V4",0.66],"stMin":["aVL",-0.23]} },
  { traceId: 'qs-15082', cardId: 'lvh-strain', f: {"rate":66,"rrCv":1.9,"qrs":100,"pr":190,"stMax":["V2",0.25],"sokolow":3.8} },
  { traceId: 'qs-16151', cardId: 'avb-3', f: {"rate":27,"rrCv":0.3,"qrs":170,"pr":178,"stMax":["V4",0.42],"stMin":["V6",-0.21]} },
  { traceId: 'qs-16271', cardId: 'avb-3', f: {"rate":37,"rrCv":1.1,"qrs":116,"qtc":446} },
  { traceId: 'qs-17669', cardId: 'lvh-strain', f: {"rate":94,"rrCv":0.7,"qrs":84,"qtc":668,"stMax":["V1",0.12],"stMin":["V6",-0.11],"sokolow":4.4} },
  { traceId: 'qs-18118', cardId: 'leftmain', f: {"rate":74,"rrCv":1.8,"qrs":88,"pr":118,"stMax":["aVR",0.15],"stMin":["V4",-0.42],"sokolow":4.6} },
  { traceId: 'qs-19164', cardId: 'avb-2', f: {"rate":79,"rrCv":26.9,"qrs":102,"pr":260,"stMax":["V2",0.14],"stMin":["II",-0.11]} },
]

export const QUIZ_BY_CARD: Record<string, QuizStrip[]> = {}
for (const s of QUIZ_STRIPS) (QUIZ_BY_CARD[s.cardId] ??= []).push(s)
