/**
 * Solver-generated conditions — the SAME engine, different tissue state. These
 * prove the propagation model: NSR (pace SA), RBBB (cut the right bundle), LBBB
 * (cut the left bundle). Nothing here authors a waveform; it all emerges from
 * geometry. The hand-curated conditions remain the reference until these match.
 */
import { Condition, Strip } from '../engine/types'
import { simulateBeat, TissueState } from '../engine/propagate'
import { RR_DEFAULT } from './helpers'

const tile = (state: TissueState, count = 3, rr = RR_DEFAULT): Strip => ({
  beats: Array.from({ length: count }, (_, i) => simulateBeat(state, i * rr)),
  durationMs: count * rr,
})

const SIM_NOTES = [
  { segment: 'QRS' as const, title: 'Emergent QRS', detail: 'Width and shape come from how far/late each region is reached — not from authored waveforms.' },
  { segment: 'T' as const, title: 'T wave (simplified)', detail: 'Concordant recovery model for now; faithful BBB T-discordance is the next refinement.' },
]

export const simNsr: Condition = {
  id: 'sim-nsr',
  name: 'Simulated — Normal sinus',
  shortName: 'Sim · NSR',
  category: 'Simulated',
  tagline: 'Generated by the propagation solver: pace from SA, no blocks.',
  criteria: ['Solver-generated', 'Pace: SA', 'No blocks'],
  story: 'SA → AV delay → His → bundles → Purkinje → ventricles',
  description:
    'Computed by the propagation engine. The SA node paces; the impulse traverses the ' +
    'conduction graph (AV delay, His, both bundle branches) and seeds the ventricular ' +
    'regions, which depolarize fast via Purkinje. The narrow QRS and normal axis EMERGE.',
  segmentNotes: SIM_NOTES,
  buildStrip: () => tile({ pace: 'SA' }),
}

export const simRbbb: Condition = {
  id: 'sim-rbbb',
  name: 'Simulated — RBBB (right bundle cut)',
  shortName: 'Sim · RBBB',
  category: 'Simulated',
  tagline: 'Same engine, right bundle ablated — watch the wide QRS emerge.',
  criteria: ['Solver-generated', 'Blocked: His→RBB', 'RV reached cell-to-cell'],
  story: 'RBB cut → RV seeded late from the septum → wide terminal forces',
  description:
    'Identical to the simulated NSR except the His→RBB edge is blocked. The right ventricle ' +
    'can no longer be reached quickly, so it is activated late through slow cell-to-cell spread ' +
    'from the septum — the wide, late rightward terminal forces of RBBB emerge on their own.',
  segmentNotes: SIM_NOTES,
  blockedBranches: ['RBB'],
  buildStrip: () => tile({ pace: 'SA', blockedEdges: ['HIS>RBB'] }),
}

export const simLbbb: Condition = {
  id: 'sim-lbbb',
  name: 'Simulated — LBBB (left bundle cut)',
  shortName: 'Sim · LBBB',
  category: 'Simulated',
  tagline: 'Same engine, left bundle ablated — the LV lags and the QRS broadens.',
  criteria: ['Solver-generated', 'Blocked: His→LBB', 'LV reached cell-to-cell'],
  story: 'LBB cut → LV seeded late from the RV/septum → broad leftward forces',
  description:
    'The His→LBB edge is blocked, so the entire left conduction system (LBB + both fascicles) ' +
    'is unreachable. The dominant left ventricle is activated late and slowly from the right — ' +
    'the broad, sustained leftward QRS of LBBB emerges from the geometry.',
  segmentNotes: SIM_NOTES,
  blockedBranches: ['LBB', 'LAF', 'LPF'],
  buildStrip: () => tile({ pace: 'SA', blockedEdges: ['HIS>LBB'] }),
}

export const simStemiAnterior: Condition = {
  id: 'sim-stemi-ant',
  name: 'Simulated — Anterior STEMI',
  shortName: 'Sim · Anterior STEMI',
  category: 'Simulated',
  tagline: 'Same engine, anterior LV ischemic — ST elevation emerges in V2–V4.',
  criteria: ['Solver-generated', 'Ischemic: anterior LV', 'Injury current → ST'],
  story: 'Anterior wall injury → ST vector points anterior → STE in V2–V4',
  description:
    'The anterior LV regions are flagged ischemic. Their injury current produces a sustained ' +
    'ST vector pointing toward the anterior chest, so the facing leads (V2–V4) show ST ' +
    'elevation with reciprocal depression inferiorly — emerging from the tissue state, not authored. ' +
    '(Localization is coarse at this region resolution.)',
  segmentNotes: [
    { segment: 'ST', title: 'ST elevation (V2–V4)', detail: 'Injury current flows toward the anterior wall during the ST segment → elevation in the leads that face it.' },
    { segment: 'QRS', title: 'Conduction intact', detail: 'No block — the QRS is normal; the abnormality is the ST injury vector.' },
  ],
  buildStrip: () => tile({ pace: 'SA', ischemic: ['LV_ant', 'LV_apex'] }),
}

export const SIM_CONDITIONS: Condition[] = [simNsr, simRbbb, simLbbb, simStemiAnterior]
